### ISSUE TITLE
Failure to import from block keeper file

### ISSUE THREAD

**Issue by ManoSegransan** [tussosedan/kuebiko-cubing#10]
I have tried uploading a block keeper export and it doesn't work. I may be because of the large file size.  
Here's a link to my export : https://mega.nz/#!LTwhFKJZ!BPx2oJs0YcXDeeFUo2V2awS1dW4d9wsl3w42rWxuieM

**Comment by tussosedan** [comment]
Oh I see what happened, you have solves that don't contained dates. Apparently dates were added to Block Keeper only around January 2018, does that sound right?
I have to think how to handle this -- maybe ignore all solves without dates when charting by date.

**Comment by ManoSegransan** [comment]
Yeah I think it's something like that. Ignoring all solves without dates doesn't bother me :)

**Comment by ManoSegransan** [comment]
Ok cool :) 

At the beginning I wanted to have one big session per aoN but Block Keeper starts to become slow when sessions are larger than 4 or 5k solves, so I switched to sessions by date. I also have some sessions where I use other methods just for fun :)

**Comment by tussosedan** [comment]
Fixed! Note that your file takes a long time to load, due to the large number of sessions (almost 80 total!), almost 3 minutes. But it does work now :)
