### ISSUE TITLE
Prisma Puzzle Timer support

### ISSUE THREAD

**Issue by AndreasAskjem** [tussosedan/kuebiko-cubing#11]
.h2.db file:
[puzzletimer.h2.zip](https://github.com/tussosedan/kuebiko-cubing/files/2636929/puzzletimer.h2.zip)

.txt file with single event:
[3x3.txt](https://github.com/tussosedan/kuebiko-cubing/files/2636935/3x3.txt)

**Comment by tussosedan** [comment]
No DNFs in 6 years? :)

**Comment by AndreasAskjem** [comment]
I got the habit of deleting them because Prisma only removes the single best and worst time (instead of 5%). I don't want to get a DNF Ao100 just because of 2 DNFs.

**Comment by tussosedan** [comment]
I see, unfortunately it turns out that quite a few timers do this.
BTW, just to verify, the data you uploaded is in a Norwegian locale?

**Comment by AndreasAskjem** [comment]
Yup

**Comment by tussosedan** [comment]
Done -- single event import is now supported. The main trouble was with the localized date strings, which are problematic to parse. If naive parsing doesn't work, I'm using a special dateparser package (which is slow). Still, under 2 minutes for your file, not too bad (or switch to US locale for faster parsing :P)
