### ISSUE TITLE
Dates Histogram

### ISSUE THREAD

**Issue by topppits** [tussosedan/kuebiko-cubing#15]
Can you show the sum of the number of solves?
Can you also show the sum of the time of all those solves?

So I'd see: on day/month/year x I did xx solves and they took xx hours.

**Comment by tussosedan** [comment]
As the histogram is dynamic, it unfortunately does not support a dynamic total. I can show such totals per bar, but not overall -- unless I add a separate overall bar, but that would be weird.

**Comment by topppits** [comment]
I see, that's too bad.

Small bug report: https://i.imgur.com/o3pf7ym.png

I don't think it's supposed to look like that. It was different before and now I can only see part of the text. Also, I don't think you need to write "sessions" before the session names, everyone should know what they are looking at.

**Comment by tussosedan** [comment]
Hmm yeah, it should be concatenated, not separate. The "Sessions" is a side effect of trying to support all timers, each with its own kinks. Originally its the puzzle and the category -- but since cstimer just has sessions, I just use "Sessions" for the puzzle name. I could use the scramble type maybe, but its not really reliable.

**Comment by tussosedan** [comment]
Fixed in f96c064612f042cd20855de73ece337ba0a27db5

**Comment by topppits** [comment]
Thx, works perfect!

Every now and then the box select isn't really working for me. Do you also have that problem or is it just me? I tried with Opera and Chrome. It draws the box and the box stays after releasing the mouse button, but that's it, nothing happens.

**Comment by tussosedan** [comment]
Great!
Hmm, what do you expect the box select to do?
