### ISSUE TITLE
Feature request: plot % sub-x over time

### ISSUE THREAD

**Issue by edladd84** [tussosedan/kuebiko-cubing#17]
This is a plot I used to add to my spreadsheet display (before I abandoned google sheets in favour of Kuebiko :D )

Basically I would input a target time (say 20s) and then plot the number of solves that were less than that in each average of hundred.  So you can see a rolling progression of you beating your target time more and more often.

![sub-20](https://user-images.githubusercontent.com/20668823/49646617-79d51680-fa17-11e8-965d-07d89d4b122c.png)

I've no idea if anyone else would be interested in this so it's probably low priority

Some complications this would add:
Need to accept a user entry for the target time
Need a second vertical scale/axis plotting %

Let me know what you think,
Ed

**Comment by tussosedan** [comment]
I love this, I'd like to have this for myself too!

The only problem is that the way I'm calculating data on server-side, and not saving any user data, I can only accept parameters that affect data generation at the time of uploading the file. And as there are different events and sessions with different target times (probably)...

Maybe I'll just start with one target time (optional), which would mean you'll have to re-upload the file to choose another target time for a different event.

**Comment by edladd84** [comment]
At the moment I'm using the histograms to get a snapshot of it.  So for PB Ao100 I can add up the columns that are sub-20 for example.

You could potentially auto-select a target time that is a milestone-type number less than their current average.  So if they average 13 pick 10 as the target number?  Or if they are 28s, pick 25.  It's a bit subjective though.

If I had any Python skillz I'd try some of it out myself to come up with possible ideas.  I can follow the code (usually) but I'm an embedded C guy - which is a fairly different perspective.  Maybe over the christmas break I'll educate myself :)

**Comment by tussosedan** [comment]
Hmm maybe the default option will indeed be the next multiple of 5, with an option to override it globally.

Dynamic changes would've been much easier had I wrote everything client-side in javascript, but when I started out I didn't know any, and anyway using python is such a joy. You should definitely learn it :)

P.S. Funny that you mention using the Christmas break for it, as Python started as a Christmas break project, heh.

**Comment by tussosedan** [comment]
Done in 1aeff64e8c9be7e8237a662428b63f133aca9f78! Phew, this was a classic case of a seemingly simple feature that took a lot of work and several iterations of refactorings. 
But now I can watch my target time approach (or not...), so it's all worth it.
Could you test and compare to your charts?

**Comment by edladd84** [comment]
I didn't even realise you were still working on this!!  Christmas come early 😄 

Looks good to me.  I had stopped using my own charts when I started using Kuebiko, so it's great to have them again.  Apparently I peaked at 40% sub-20 a few days ago!!  So I'm happy with that.  I just need to start cutting out the sup-30s now

**Comment by tussosedan** [comment]
Heheh happy holidays :)
