### ISSUE TITLE
No clue what is wrong, simply not importing

### ISSUE THREAD

**Issue by KnoxLing2** [tussosedan/kuebiko-cubing#20]
[cstimer_20181225_205715.txt](https://github.com/tussosedan/kuebiko-cubing/files/2709301/cstimer_20181225_205715.txt)

**Comment by tussosedan** [comment]
Thanks for reporting it -- looks like I broke something while improving handling of special characters. Fixed in 34294af6cbbe42062e4cdf86eefac8b7a5e23bd0.
