### ISSUE TITLE
Enhancement: Allows users to choose the percentage used for calculating the trimmed mean. 

### ISSUE THREAD

**Issue by abrunell** [tussosedan/kuebiko-cubing#21]
Currently, the site calculates the trimmed average by discarding the top and bottom 5% of solves. It would be useful if a user could choose which percentage is being used, maybe in the advanced options section when submitting a file.

**Comment by tussosedan** [comment]
5% is the industry standard, and I believe using something different will cause confusion. What would it be useful for?

**Comment by abrunell** [comment]
Let's say someone does a session of 100 solves, and they feel like they did extremely well, except they had an abnormal number of flubs that caused them to have a number of really bad times (maybe that day they slipping up on G perms, thus scrambling the cube). In that case, their distribution--and thus their average--would be pretty skewed. They wonder if their solve time has improved, other than the solves where they severely messed up a PLL alg. 

If they could change the trim to 10% simply for the sake of comparing this ao100 to previous ones, they would see that their normal solve time is indeed improving. 

It's probably not a feature that would get a ton of use, but I thought it might be easy to add since you just need to change a variable somewhere based on an input. It would be an "advanced" option, so 5% would still be the default. 

It's totally cool if you're not into it, though!

**Comment by clarknt** [comment]
Commit 4d41955 has been discarded and can be ignored, it was on the wrong branch. Pull request has been made with the correct commit 4ca83bf.

**Comment by tussosedan** [comment]
Looking good, thank you! I added a small comment.

**Comment by tussosedan** [comment]
In the pull request.

**Comment by clarknt** [comment]
Somehow I cannot see it, there's only my own comment (the commit log) in the "Conversation" tab? And no comment to specific lines under "Files changed" either.

**Comment by tussosedan** [comment]
@clarknt thank you for your work!
