### ISSUE TITLE
solve# for WCA id isn't calculated correctly for events with less than 5 solves per round

### ISSUE THREAD

**Issue by topppits** [tussosedan/kuebiko-cubing#22]
choose event, go to PBs or Top50. The Solve # is calculated as if I had 5 solves per round, whatever event it is. For 3BLD e.g. that should only be 3 and also DNS shouldn't be counted as a solve. 

In the Dates Histogram it also shows 5 solves * # of rounds, whatever event you have.

Also multi blind is completely missing.

**Comment by tussosedan** [comment]
Thanks for the report, counting of "no result" and DNS should be solved now.
Multiblind (and FMC) are currently not supported, as the system can handle only time results as it is now.
