### ISSUE TITLE
File can't be read (SkipTimer)

### ISSUE THREAD

**Issue by iSach** [tussosedan/kuebiko-cubing#24]
Hello,

I tried using the data I exported from the Skip Timer app:
https:// https://puu.sh/CAH2P/7aeee1d7e8.txt

But it doesn't work, any ideas why?

Thanks a lot

**Comment by tussosedan** [comment]
Probably because Skip Timer is not on the list of supported timers :)
That data looks suspiciously similar -- yet not identical -- to data. Weird.

**Comment by iSach** [comment]
I know it's not really officially supported, but he made it similar enough to work I thought:
https://twitter.com/DarioRubik/status/1087047965146079232

**Comment by tussosedan** [comment]
Wow, didn't know about that, nice! No idea how it worked for him. There's a whole chunk of metadata missing at the end, for starters. Are you able to import it into cstimer (and maybe then export from there)?

**Comment by iSach** [comment]
Yes, I can. Howeever, some sessions including one with 1500 solves don't seem to work and just show as "empty" on the CSTimer import thing:
https://puu.sh/CAJJF/7b270f3483.png

**Comment by darioroa** [comment]
Working on a fix.

**Comment by darioroa** [comment]
@tussosedan  Do you have any suggestions regarding the missing metadata? I decided to follow a similar pattern to cstimer, but if there's a simpler way to implement it, I'm interested in that too.

**Comment by tussosedan** [comment]
I basically only use the session names from the sessionData in properties. But you could also go with the simpler CSV format, like TwistyTimer.
