### ISSUE TITLE
Block keeper: merge sessions option

### ISSUE THREAD

**Issue by clarknt** [tussosedan/kuebiko-cubing#28]
# Use case
With Block Keeper, events are categorized and a user can choose to have multiple sessions for the same event. Example with one or more sessions per day:
- 3x3x3
  - 01/02/2019
  - 02/02/2019
  - 03/02/2019
  - 03/02/2019 2
  - 05/02/2019
  - 09/02/2019
  - 10/02/2019
- 4x4x4
  - 02/02/2019
  - 04/02/2019
  - 04/02/2019 2
  - 04/02/2019 3
  - 14/02/2019
- etc.

As a result, multiple small sessions are shown within kuebiko-cubing and are not very significant as a whole.

Furthermore, they are sorted alphabetically, which is not ideal if default session name is used on a system with a DD/MM/YYYY date format.

# Enhancement suggestion
Add an option to merge Block Keeper sessions by event when importing.

**Comment by clarknt** [comment]
If considered useful I can work on that.

**Comment by tussosedan** [comment]
Thanks for the suggestion. An option to merge by puzzle (in Kuebiko's terms) would be good to have, and should be straightforward to implement -- simply override the category name to something like "Merged". It should work not only for Block Keeper but any timer that maintains such a hierarchy, like Twisty Timer (basically any timer data that has both puzzle and category names).

I have less free time to work on Kuebiko lately, so if you'd like to take this one it would be great.

**Comment by clarknt** [comment]
Would you happen to have sample data for each supported timer? Could be useful to do some tests.

**Comment by tussosedan** [comment]
I have some files, but I'm not sure I can share them as they're not mine. You can always generate your own files.

**Comment by tussosedan** [comment]
Looks great, thanks!
