### ISSUE TITLE
PB list for averages

### ISSUE THREAD

**Issue by dancing-jules** [tussosedan/kuebiko-cubing#3]
Currently there's only a pb list for the pb single. It would be nice to also have a list for averages, so you can quickly see when the pb average was set, without sifting through the chart. 

As you said though, the bigger the average the longer that list.

So if that's not feasible. At least having a list of all current pb averages would be nice. That way they can be easily copied into cubepb, for example.

**Comment by tussosedan** [comment]
You got it!
