### ISSUE TITLE
Unable to upload ChaoTimer Files 

### ISSUE THREAD

**Issue by langstonmandela** [tussosedan/kuebiko-cubing#31]
[July 2019.txt](https://github.com/tussosedan/kuebiko-cubing/files/3503121/July.2019.txt)
I attempted to upload a chao file to check out the latest feature updates to no avail. Thanks for looking into this, I gotta visualize this data!

**Comment by tussosedan** [comment]
Yup I broke something. On it.

**Comment by tussosedan** [comment]
Fixed in 0261054831884d8d8b31d63e2e3621b7ff6a0ae1

**Comment by langstonmandela** [comment]
Right on, thanks!
