### ISSUE TITLE
Failure to import from TwistyTimer file

### ISSUE THREAD

**Issue by AshleyF** [tussosedan/kuebiko-cubing#4]
I can't seem to upload my TwistyTimer export (attached). Simply says: "Something went wrong while reading the file. Please open an issue on the github page and upload the file there."

[Backup_24-Nov-2018_13-48.txt](https://github.com/tussosedan/kuebiko-cubing/files/2612613/Backup_24-Nov-2018_13-48.txt)

**Comment by tussosedan** [comment]
Heya Ashley! I see what happened here, it's due to the clock DNFs heheh. I'll add a fix to ignore all-DNF cases in a few days, but as a workaround for now just remove the clock lines from the file.

**Comment by tussosedan** [comment]
fixed!
