### ISSUE TITLE
Gaps in averages of 50, 100, 1000 while displaying solves by solve #

### ISSUE THREAD

**Issue by abrunell** [tussosedan/kuebiko-cubing#5]
See attached images. The gaps in the line graphs only appear towards the end of the chart, starting around solve 7555. There are data points in these gaps, though, so it seems there's some problem with either the average calculation, or the displaying of those averages. 

Note that the two images are of the same data. One shows the single data points, the other doesn't. 

![image](https://user-images.githubusercontent.com/8592266/48996866-52c33e80-f113-11e8-8581-87ddf3819a3b.png)

![image](https://user-images.githubusercontent.com/8592266/48997330-2dcfcb00-f115-11e8-94a0-6ca3e52649d4.png)

**Comment by tussosedan** [comment]
Thanks for reaching out! This usually happens due to averages actually being DNFs -- when there are still counting DNFs after trimming 5% top and bottom. Could you verify it in your data?

**Comment by abrunell** [comment]
Ah, that's what's going on, I think.
