### ISSUE TITLE
Dotted line for pb does not continue after latest pb

### ISSUE THREAD

**Issue by dancing-jules** [tussosedan/kuebiko-cubing#6]
![Here](https://user-images.githubusercontent.com/33940391/49046946-21f80d80-f1d6-11e8-8f37-25102999412e.png) - the dotted line should continue to the present day. I guess this bug is a side-effect from fixing the other issue.

**Comment by tussosedan** [comment]
This isn't actually a bug, as no further PBs have been set -- so there's no reason for the line to continue. Still, I agree it could be nicer to have the line to the end, maybe by adding the same PB again at the end with a "(continued)" label or such.

**Comment by dancing-jules** [comment]
If I haven't set a new pb, my old one still stands. I'd just continue the dashed line without a solid dot at the end.

**Comment by tussosedan** [comment]
Well this was much less trivial than expected, but I really like how it turned out.
