### ISSUE TITLE
Adding support for ZYX Timer CSV output

### ISSUE THREAD

**Issue by edladd84** [tussosedan/kuebiko-cubing#8]
Attached is the example output from ZYXTimer (iOS App).  This CSV is emailed to the user on request in the app, I have pasted the content of the email into this text file.  Note that ZYXTimer does not generate a file, so it would be more straightforward to have a text box input on this site to paste the email into maybe?  There is also the option to "copy session" in the app, so the whole operation could be achieved on mobile by copying in ZYX Timer and pasting in Kuebiko.

There are two options for export - 'current session' and 'all sessions'.  Examples of both are provided if you would like to support them.

This session contains examples of DNF, +2, and the formatting for times >1 minute.  If you would like any further example outputs let me know.

[ZYXTimer_single_session_export.txt](https://github.com/tussosedan/kuebiko-cubing/files/2629215/ZYXTimer_single_session_export.txt)
[ZYXTimer_multi_session_export.txt](https://github.com/tussosedan/kuebiko-cubing/files/2629216/ZYXTimer_multi_session_export.txt)

Cheers,
Ed

**Comment by tussosedan** [comment]
Do you mean that the email sent by ZYXTimer includes the times in the actual body of the email, and not as an attachment? There is no way to make it generate a file?

Also, for these single and multi sessions, could you share the stats (aoX etc) that the timer shows you -- so I'll be able to check it vs my calculations?

**Comment by edladd84** [comment]
Yes - the times are in the body of the email.  I'll send you one directly as an example. (tussosedan@kuebiko-cubing.com)

ZYX Timer has a few bugs, and I don't think the devs work on it anymore.  I submitted a bug report to them and the email bounced back.  One of the bugs is that the PB averages sometimes increase!  So for example, I know my PB Ao5 is 18.83, but the app reports it as 19.35 (even though it used to be correct in the app.)

FWIW - here are the PB averages from each of the sessions in the multi session file (the single session is the CN session from the multi, plus a few solves I did at lunchtime):
| Session name | Total Num solves | Ao5 | Ao12 | Ao50 | Ao100 | Ao1000 |
| --- | --- | --- | --- | --- | --- | --- |
| CN | 5733 | 19.35 | 20.40 | 21.51 | 22.17 | 23.22 |
| 2x2 | 1088 | 5.40 | 6.44 | 7.23 | 7.96 | 10.10 |
| 4x4 | 900 | 1:20.05 | 1:25.78 | 1:31.09 | 1:32.74 | 0.00 |
| 5x5 | 121 | 3:56.27 | 4:03.79 | 4:14.58 | 4:34.98 | 0.00 |
| Minx | 108 | 3:28.58 | 3:37.81 | 3:59.59 | 4:46.92 | 0.00 |
| One Hand | 332 | 42.13 | 47.59 | 54.76 | 59.80 | 0.00 |
| Blind | 6 | 0.00 | 0.00 | 0.00 | 0.00 | 0.00 |
| Other | 271 | 20.58 | 21.76 | 23.55 | 25.08 | 0.00 |

**Comment by edladd84** [comment]
Bah - table formatting eludes me :(

**Comment by tussosedan** [comment]
Wow that's one messed up way to export data, LOL. Thanks, this should give me all I need to make it happen.

**Comment by edladd84** [comment]
Sent you a new email, also copied the relevant section below:

40.21, 57.27, 55.72, 1:08.75, 45.98[this solve has a, comment]

**Comment by edladd84** [comment]
Also - in case it comes up.  If a session name has a comma, this is how it looks:

 3:34.91, 3:09.60

Session: One, Hand
3:04.24, 1:47.88, 1:59.63, 1:34.10, 1:32.16, 1:47.22, 2:18.86, 1:43.66, 2:02.56, 2:27.05, 1:53.07, 1:40.16, 1:24.50, 52.38, 1:21.73, 1:24.20, 1:32.04, 1:35.39, 1:21.46, 1:24.02, 1:20.85, 1:47.84, 59.52, 1:15.89, 1:27.38, 51.25, 1:26.33, 1:05.92, 1:05.83, 1:22.72, 58.41, 1:24.65, 1:02.32, 57.30, 1:13.42, 1:46.81,

**Comment by tussosedan** [comment]
Is the "copy session" option only for a single session, or can it be for all sessions too?

**Comment by edladd84** [comment]
Copy session has options for one session or all - the format is the same as the email.

The '+' indicates that a 2 needs to be added, so a 42.32+ is actually 44.32.

Adding [ ] to comments can totally screw with the parser - you've already thought about this more than the devs :).  It will generate a single solve that looks like two solves.  If you re-import that back into the app, it will actually insert them as two different solves.

**Comment by tussosedan** [comment]
Hahaha all righty then. I'm making good progress with this.

**Comment by tussosedan** [comment]
Done!

**Comment by edladd84** [comment]
Is this live yet?  I'm still getting an error "Looks like this file type is not supported yet. Please open an issue on the github page and upload the file there."  This happens if I use the paste box or a file.  If it is supposed to be working let me know and I'll provide more details.

**Comment by tussosedan** [comment]
Yup, just make sure you're using the "all sessions" export/copy.

![image](https://user-images.githubusercontent.com/32999689/49367000-72e69500-f6f3-11e8-99b9-2211bbeddfb9.png)

**Comment by edladd84** [comment]
My bad - was doing a single session - thanks for that again.
